==============================================================================
                     __  __
                     \ \/ /___ __  __ ___  ___  ___
                      \  // _ \\ \/ /,-_ |/ _ |/ -_)
                       \/ \___/ \  / \___,\_  |\___|
                               _/_/        _'_|
                         { V o y a g e } - L i n u x
                          < http://linux.voyage.hk >

  1. PXE Boot Voyage Linux with a login shell (*default*)
  2. Start automated install for WRAP (/dev/sda and 38400 serial console)
  3. Start automated install for ALIX (/dev/sda and 38400 serial console)
  4. Start automated install for APU (/dev/sda and 115200 serial console)
  5. Start automated install for 45/48xx (/dev/sda and 19200 serial console)
  6. Start automated install for 55xx (/dev/sda and 19200 serial console)
  7. Start automated install for 6501 (/dev/sda and 19200 serial console)
  8. Start automated install for gerenic PC (/dev/sda and no serial console)

==============================================================================
