#!/bin/sh

# /usr/share/live-helper/hooks/stripped - hook list for live-helper(7)
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.


echo "($0)"

# We'll use this to create the initrd.img as other things seem to break
if [ ! -f /boot/initrd.img-* ]; then
        for K in `ls /lib/modules/ `; do
                update-initramfs -c -k $K
                ln -s /boot/initrd.img-$K /initrd.img
                ln -s /boot/vmlinuz-$K /vmlinuz
        done
fi

