#!/bin/sh

sed -i -e "s/ath/Ath/" /etc/udev/rules.d/*_persistent-net-generator.rules

# the workaround 
rm -f /etc/udev/rules.d/*persistent-net.rules
rm -f /etc/udev/rules.d/*persistent-net-generator.rules

######################################

#rm -f /dev/*
#mknod /dev/console c 5 1
#mknod /dev/null c 1 3

cat <<EOF>/etc/udev/rules.d/mount-usb.rules 
## usb disk comes up too late for /etc/init.d/mountall.sh
ENV{ID_FS_LABEL}=="usbrw", ACTION=="add", RUN+="/bin/mount /dev/%k"
ENV{ID_FS_LABEL}=="usbmedia", ACTION=="add", RUN+="/bin/mount /dev/%k" 
EOF
