#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading extra kernel bits into the initramfs

. /usr/share/initramfs-tools/hook-functions

# Copy modules.dep
#echo "Copy ${MODULESDIR}/modules.dep  ${DESTDIR}/${MODULESDIR}/"
cp -a ${MODULESDIR}/modules.dep  ${DESTDIR}/${MODULESDIR}/

