==============================================================================
                     __  __
                     \ \/ /___ __  __ ___  ___  ___
                      \  // _ \\ \/ /,-_ |/ _ |/ -_)
                       \/ \___/ \  / \___,\_  |\___|
                               _/_/        _'_|
                         { V o y a g e } - L i n u x
                          < http://linux.voyage.hk >

  1. PXE Boot Voyage Linux with a login shell
  2. Start automated install for WRAP (/dev/hda and 38400 serial console)
  3. Start automated install for ALIX (/dev/hda and 38400 serial console)
  4. Start automated install for 45/48xx (/dev/hda and 19200 serial console)
  5. Start automated install for 55xx (/dev/hda and 19200 serial console)
  6. Start automated install for gerenic PC (/dev/hda and no serial console)

==============================================================================
