#!/bin/sh

# Used to set the hostname here, but it works better to set it in
# config/chroot_local-includes/etc, along with the hosts file.
# Still need a blank /etc/hostname file at this point to keep some other 
# scripts happy, so just touch it.

touch /etc/hostname
