#!/bin/sh


#################################
# Modifying /etc/init.d/syslogd
#################################
#echo -n "Modifying /etc/init.d/syslogd ... "
#cat $DEST/etc/init.d/sysklogd | \
#sed -e 's/^SYSLOGD=\"\"/SYSLOGD\=\"\-p \/rw\/dev\/log \-m 0\"/' \
#>  $DEST/etc/init.d/sysklogd.tmp
#mv  $DEST/etc/init.d/sysklogd.tmp  $DEST/etc/init.d/sysklogd
#chmod +x $DEST/etc/init.d/sysklogd
#echo "Done"

#################################
# Modifying /etc/mtab
#################################
echo -n "Modifying /etc/mtab ... "
rm -f /etc/mtab
ln -s /proc/mounts /etc/mtab
echo "Done"

#################################
# Modifying /etc/network/options
#################################
#echo -n "Modifying /etc/network/options ... "
#touch /etc/network/options 
#echo ip_forward=yes >> /etc/network/options 
#echo spoofprotect=yes >> /etc/network/options 
#echo syncookies=no >> /etc/network/options 
##sed -i -e "s/ip_forward=no/ip_forward=yes/" /etc/network/options 
#echo "Done"

#################################
# Modifying /etc/dnsmasq.conf
#################################
echo -n "Modifying /etc/dnsmasq.conf ... "
DNSMASQ_CONF=/etc/dnsmasq.conf 
DNSMASQ_MORE_CONF=/etc/dnsmasq.more.conf
if [ -f $DNSMASQ_CONF ] ; then
	echo "conf-file=$DNSMASQ_MORE_CONF" >> $DNSMASQ_CONF
fi	
#echo "dhcp-leasefile=/var/tmp/dnsmasq.leases" >> $DNSMASQ_MORE_CONF
#echo "dhcp-range=wlan0,10.1.10.10,10.1.10.250,24h" >> $DNSMASQ_MORE_CONF
#echo "dhcp-range=eth1,10.1.20.10,10.1.20.250,24h" >> $DNSMASQ_MORE_CONF
#echo "dhcp-range=eth2,10.1.30.10,10.1.30.250,24h" >> $DNSMASQ_MORE_CONF
#echo "dhcp-range=eth3,10.1.40.10,10.1.40.250,24h" >> $DNSMASQ_MORE_CONF
echo "Done"
	
#################################
# Adding configuration for watchdog
#################################
echo -n "Adding configuration for watchdog ... "
WATCHDOG_CONF=/etc/watchdog.conf
if [ -f $WATCHDOG_CONF ] ; then
	echo "watchdog-device = /dev/watchdog" >> $WATCHDOG_CONF
	echo "interval	    = 15" >> $WATCHDOG_CONF
	mknod -m 600 /dev/wd c 10 130
fi;
echo "Done"

#################################
# Modifying /etc/init.d/mountall.sh
#################################
#echo -n "Modifying /etc/init.d/mountall.sh ... "

mkdir /ro
#echo "tar -C /ro -cf - . | tar -C /lib/init/rw -xf -  > /dev/null 2>&1" >> /etc/init.d/mountall.sh

#cat >> /etc/init.d/mountall.sh <<EOF
#mkdir -p /rw/var/log > /dev/null 2>&1
#mount -t aufs -o dirs=/rw/var/log:/var/log=ro none /var/log  > /dev/null 2>&1
#mkdir -p /rw/var/tmp > /dev/null 2>&1
#mount -t aufs -o dirs=/rw/var/tmp:/var/tmp=ro none /var/tmp  > /dev/null 2>&1
#mkdir -p /rw/tmp > /dev/null 2>&1
#mount -t aufs -o dirs=/rw/tmp:/tmp=ro none /tmp  > /dev/null 2>&1
#EOF

#echo "Done"

#################################
# Enable RAMRUN and RAMLOCK in /etc/default/rcS
#################################
echo -n "Enable RAMRUN and RAMLOCK in /etc/default/rcS"
cat >> /etc/default/rcS <<EOF
RAMRUN=yes
RAMLOCK=yes
EOF
echo "Done"

#################################
# Add voyage-sync to rc.d
#################################
#echo -n "Add voyage-sync to rc.d "

#update-rc.d voyage-sync start 36 S . start 36 0 6 .
#mv /etc/rc0.d/K99voyage-sync /etc/rc0.d/S36voyage-sync 
#mv /etc/rc6.d/K99voyage-sync /etc/rc6.d/S36voyage-sync 


#################################
# Modifying /etc/modules
#################################
echo -n "Modifying /etc/modules ... "
echo "natsemi" >> /etc/modules
echo "Done"

#################################
# Modifying /etc/sysctl.conf
#################################
echo -n "Modifying /etc/sysctl.conf ... "
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.rp_filter=1" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.rp_filter=1" >> /etc/sysctl.conf
echo "net.ipv4.tcp_syncookies=0" >> /etc/sysctl.conf
echo "kernel.panic=30" >> /etc/sysctl.conf
echo "Done"

#################################
# Modifying /root/.bashrc
#################################
echo -n "Modifying /root/.bashrc ... "
echo ". /etc/bash_completion" >> /root/.bashrc
echo "Done"

#################################
# Modifying /etc/hosts
#################################
echo -n "Modifying /etc/hosts ... "
echo "127.0.0.1 localhost hamlinux" >> /etc/hosts
echo "127.0.1.1 hamlinux" >> /etc/hosts
echo "Done"


#################################
# Modifying /etc/apt/sources.list
#################################
echo -n "Modifying /etc/apt/sources.list ... "
echo "" >> /etc/apt/sources.list
echo "# Primary Debian Mirror Sites (http://www.debian.org/mirror/list)" >> /etc/apt/sources.list
wget http://www.debian.org/mirror/list -O - | \
sed -n  -e "/td><a href=\"http:\/\/ftp\.[a-z][a-z]/ P" | \
sed -e "s/^.*a href=\"//g" -e "s/\">.*$//g" -e "s/^/#deb /g " -e "s/$/ lenny main contrib non-free/g" | sort \
>> /etc/apt/sources.list

echo "Done"
