#!/bin/sh

# /usr/share/live-helper/hooks/stripped - hook list for live-helper(7)
# Copyright (C) 2006-2008 Daniel Baumann <daniel@debian.org>
#
# live-helper comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
# This is free software, and you are welcome to redistribute it
# under certain conditions; see COPYING for details.

set -e

echo "($0)"

for K in `ls /lib/modules/ `; do
	update-initramfs -c -k $K
done

if [ $(dpkg-query --show | cut -f1 | grep "^gcc$" | wc -l) -gt 0  ] ; then
    echo "($0) Building Voyage SDK.  No purging."

else
	if [ $(dpkg-query --show | cut -f1 | grep "^asterisk$" | wc -l) -gt 0  ] ; then
    	echo "($0) Building Voyage ONE.  "
		PURGE_PKGS="man-db manpages info dselect"
	elif  [ $(dpkg-query --show | cut -f1 | grep "^mpd$" | wc -l) -gt 0 ] ; then
        	echo "($0) Building Voyage MPD.  "
        	PURGE_PKGS="man-db manpages info dselect"
	else
        	echo "($0) Building Voyage Linux.  "
		PURGE_PKGS="aptitude man-db manpages info dselect live-config live-config-sysvinit live-boot live-boot-initramfs-tools"
		PURGE_PKGS="aptitude man-db mAnpages info dselect perl perl-modules"
	fi

	# Removing unused packages
	for PACKAGE in `echo "$PURGE_PKGS" |sed -e "s/ /\n/g"`
	do
		echo "*** Removing package "$PACKAGE""
		if ! apt-get remove --purge --yes "${PACKAGE}"
		then
			echo "WARNING: ${PACKAGE} isn't installed"
		fi
	done

	apt-get autoremove --yes || true

	rm -rf /usr/include/*
	#rm -rf /usr/share/groff/*
	rm -rf /usr/share/doc/*
	rm -rf /usr/share/locale/*
	rm -rf /usr/share/man/*
	rm -rf /usr/share/i18n/*
	rm -rf /usr/share/info/*
	rm -rf /usr/share/lintian/*
	rm -rf /usr/share/linda/*
	#rm -rf /usr/share/zoneinfo/*
	rm -rf /var/cache/man/*
fi

# Removing unused files
find . -name *~ | xargs rm -f

# Cleaning apt lists
rm -rf /var/lib/apt/lists
mkdir -p /var/lib/apt/lists/partial

# Cleaning apt cache
rm -rf /var/cache/apt
mkdir -p /var/cache/apt/archives/partial

# Truncating logs
for FILE in $(find /var/log/ -type f)
do
	: > ${FILE}
done

# at last, remove .svn
find / -name ".svn" -exec rm -rf '{}' '+'
