#! /bin/sh
set -e

#This script is here because trying to put preinst_hooks=update-grub in the 
#kernel-img.conf file gets clobbered by the live-build scripts.
#So, instead we use a script dropped in preinst.d to do the same thing.

which update-grub >/dev/null 2>&1 || exit 0

exec update-grub 0

exit 0
